name: Auto Push Updates

on:
  push:
    paths:
      - powerautomate/**
      - powerapps/**
  workflow_dispatch:
jobs:
  auto-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure Git
        run: |
          git config user.name 'ahsan-f'
          git config user.email 'ahsan.farooqui2001@gmail.com'
      - name: Commit and Push Changes
        run: |
          git add .
          git commit -m 'Auto update from workflow' || echo 'No changes to commit'
          git push
